spring.application.name: awesome-pizza

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/awesome-pizza?useSSL=false&serverTimezone=CET
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect